######################################################
######################################################
############# Request flix-api ACTORS ################
######################################################
######################################################
######################################################

@hostname = 127.0.0.1
@port = 8000

###
# @name createToken
POST http://{{ hostname }}:{{ port }}/api/v1/auth/token/
Content-Type: application/json

{
  "username": "mytoken",
  "password": "Token2024"
}

###
GET http://{{ hostname }}:{{ port }}/api/v1/actors/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxMDY5Njc3LCJpYXQiOjE3MjEwNjkzNzcsImp0aSI6ImY0NDM5MzJlODk0YzQ4NDNhZmI0OWMyZjczYjA1ZGFlIiwidXNlcl9pZCI6MX0.hBg_pE6LfE3Q-stqCJgsvzDIicbmsQJx2Py0Ey2Ab3Q

###
# @name createActor
POST http://{{ hostname }}:{{ port }}/api/v1/actors/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxMDY2OTE2LCJpYXQiOjE3MjEwNjY2MTYsImp0aSI6Ijc5YzIwNzNlYjE5OTQzYmE4ZjEwNTlmMjMzYTAzYmRiIiwidXNlcl9pZCI6MX0.QWFlqJFNnfiavMgQk7AlKPI4jxqoeqDeMwoseOJSAz0
Content-Type: application/json

{
  "name": "Silvester Stalone",
  "birthday": "1990-03-01",
  "nationality": "American"
}

###

@actorID = {{ createActor.response.body.id }}

###
GET http://{{ hostname }}:{{ port }}/api/v1/actors/{{ actorID }}/


###
PUT http://{{ hostname }}:{{ port }}/api/v1/actors/{{ actorID }}/
Content-Type: application/json

{
  "name": "Silvester Stalone Rambo",
  "nationality": "Mexican"
}

###
DELETE http://{{ hostname }}:{{ port }}/api/v1/actors/{{ actorID }}/