######################################################
######################################################
############# Request flix-api ACTORS ################
######################################################
######################################################
######################################################

@hostname = 127.0.0.1
@port = 8000

###
# @name createToken
POST http://{{ hostname }}:{{ port }}/api/v1/auth/token/
Content-Type: application/json

{
  "username": "Cinemark",
  "password": "djangomaster"
}

###
GET http://{{ hostname }}:{{ port }}/api/v1/actors/
Authorization: Bearer {{ createToken.response.body.access }}

###
# @name createActor
POST http://{{ hostname }}:{{ port }}/api/v1/actors/
Authorization: Bearer {{ createToken.response.body.access }}
Content-Type: application/json

{
  "name": "Silvester Stalone",
  "birthday": "1990-03-01",
  "nationality": "American"
}

###

@actorID = {{ createActor.response.body.id }}

###
GET http://{{ hostname }}:{{ port }}/api/v1/actors/{{ actorID }}/
Authorization: Bearer {{ createToken.response.body.access }}

###
PUT http://{{ hostname }}:{{ port }}/api/v1/actors/{{ actorID }}/
Authorization: Bearer {{ createToken.response.body.access }}
Content-Type: application/json

{
  "name": "Silvester Stalone Rambo",
  "nationality": "Mexican"
}

###
DELETE http://{{ hostname }}:{{ port }}/api/v1/actors/{{ actorID }}/
Authorization: Bearer {{ createToken.response.body.access }}