######################################################
######################################################
############# Request flix-api ACTORS ################
######################################################
######################################################
######################################################

@hostname = 127.0.0.1
@port = 8000

###
# @name createToken
POST http://{{ hostname }}:{{ port }}/api/v1/auth/token/
Content-Type: application/json

{
  "username": "mytoken",
  "password": "Token2024"
}