######################################################
######################################################
############# Request flix-api GENRES ################
######################################################
######################################################
######################################################

@hostname = 127.0.0.1
@port = 8000


###
# @name createToken
POST http://{{ hostname }}:{{ port }}/api/v1/auth/token/
Content-Type: application/json

{
  "username": "usuario",
  "password": "NovaSenha100"
}

###
GET http://{{ hostname }}:{{ port }}/api/v1/genres/
Authorization: Bearer {{ createToken.response.body.access }}

###
# @name createGenre
POST http://{{ hostname }}:{{ port }}/api/v1/genres/
Authorization: Bearer {{ createToken.response.body.access }}
Content-Type: application/json

{
  "name": "Ação"
}

###

@genreID = {{ createGenre.response.body.id }}

###
GET http://{{ hostname }}:{{ port }}/api/v1/genres/{{ genreID }}/
Authorization: Bearer {{ createToken.response.body.access }}

###
PUT http://{{ hostname }}:{{ port }}/api/v1/genres/{{ genreID }}/
Authorization: Bearer {{ createToken.response.body.access }}
Content-Type: application/json

{
  "name": "Ação Pesada"
}

###
DELETE http://{{ hostname }}:{{ port }}/api/v1/genres/{{ genreID }}/
Authorization: Bearer {{ createToken.response.body.access }}