######################################################
######################################################
############# Request flix-api GENRES ################
######################################################
######################################################
######################################################

@hostname = 127.0.0.1
@port = 8000


GET http://{{ hostname }}:{{ port }}/api/v1/genres/

###
# @name createGenre
POST http://{{ hostname }}:{{ port }}/api/v1/genres/
Content-Type: application/json

{
  "name": "Ação"
}

###

@genreID = {{ createGenre.response.body.id }}

###
GET http://{{ hostname }}:{{ port }}/api/v1/genres/{{ genreID }}/


###
PUT http://{{ hostname }}:{{ port }}/api/v1/genres/{{ genreID }}/
Content-Type: application/json

{
  "name": "Ação Pesada"
}

###
DELETE http://{{ hostname }}:{{ port }}/api/v1/genres/{{ genreID }}/