######################################################
######################################################
############# Request flix-api MOVIES ################
######################################################
######################################################
######################################################

@hostname = 127.0.0.1
@port = 8000


###
# @name createToken
POST http://{{ hostname }}:{{ port }}/api/v1/auth/token/
Content-Type: application/json

{
  "username": "cinemark",
  "password": "djangomaster"
}

###
GET http://{{ hostname }}:{{ port }}/api/v1/movies/
Authorization: Bearer {{ createToken.response.body.access }}

###
GET http://{{ hostname }}:{{ port }}/api/v1/movies/stats/
Authorization: Bearer {{ createToken.response.body.access }}

###
# @name createMovie
POST http://{{ hostname }}:{{ port }}/api/v1/movies/
Authorization: Bearer {{ createToken.response.body.access }}
Content-Type: application/json

{
    "title": "Tropa de Elite",
    "release_date": "2007-08-17",
    "resume": "Os acontecimentos do filme são narrados em primeira pessoa pelo Capitão Roberto Nascimento, dando uma perspectiva ao espectador de todos os fatos interligados.",
    "genre": 22,
    "actors": [3, 7, 9, 18]
}

###

@movieID = {{ createMovie.response.body.id }}

###
GET http://{{ hostname }}:{{ port }}/api/v1/movies/{{ movieID }}/
Authorization: Bearer {{ createToken.response.body.access }}


###
PUT http://{{ hostname }}:{{ port }}/api/v1/movies/{{ movieID }}/
Authorization: Bearer {{ createToken.response.body.access }}
Content-Type: application/json

{
    "title": "Rambo IV",
    "release_date": "1990-01-01",
    "resume": "Filme do Rambo, muito massa. Bom elenco",
    "genre": 1,
    "actors": [1]
}

###
DELETE http://{{ hostname }}:{{ port }}/api/v1/movies/{{ movieID }}/
Authorization: Bearer {{ createToken.response.body.access }}