######################################################
######################################################
############# Request flix-api MOVIES ################
######################################################
######################################################
######################################################

@hostname = 127.0.0.1
@port = 8000


###
# @name createToken
POST http://{{ hostname }}:{{ port }}/api/v1/auth/token/
Content-Type: application/json

{
  "username": "Cinemark",
  "password": "djangomaster"
}

###
GET http://{{ hostname }}:{{ port }}/api/v1/movies/
Authorization: Bearer {{ createToken.response.body.access }}

###
GET http://{{ hostname }}:{{ port }}/api/v1/movies/stats/
Authorization: Bearer {{ createToken.response.body.access }}

###
# @name createMovie
POST http://{{ hostname }}:{{ port }}/api/v1/movies/
Authorization: Bearer {{ createToken.response.body.access }}
Content-Type: application/json

{
    "title": "Rambo IV",
    "release_date": "1990-01-01",
    "resume": "Filme do Rambo, muito massa",
    "genre": 1,
    "actors": [1]
}

###

@movieID = {{ createMovie.response.body.id }}

###
GET http://{{ hostname }}:{{ port }}/api/v1/movies/{{ movieID }}/
Authorization: Bearer {{ createToken.response.body.access }}


###
PUT http://{{ hostname }}:{{ port }}/api/v1/movies/{{ movieID }}/
Authorization: Bearer {{ createToken.response.body.access }}
Content-Type: application/json

{
    "title": "Rambo IV",
    "release_date": "1990-01-01",
    "resume": "Filme do Rambo, muito massa. Bom elenco",
    "genre": 1,
    "actors": [1]
}

###
DELETE http://{{ hostname }}:{{ port }}/api/v1/movies/{{ movieID }}/
Authorization: Bearer {{ createToken.response.body.access }}