######################################################
######################################################
############# Request flix-api MOVIES ################
######################################################
######################################################
######################################################

@hostname = 127.0.0.1
@port = 8000


GET http://{{ hostname }}:{{ port }}/api/v1/movies/

###
# @name createMovie
POST http://{{ hostname }}:{{ port }}/api/v1/movies/
Content-Type: application/json

{
    "title": "Rambo IV",
    "release_date": "1990-01-01",
    "resume": "Filme do Rambo, muito massa",
    "genre": 1,
    "actors": [1]
}

###

@movieID = {{ createMovie.response.body.id }}

###
GET http://{{ hostname }}:{{ port }}/api/v1/movies/{{ movieID }}/


###
PUT http://{{ hostname }}:{{ port }}/api/v1/movies/{{ movieID }}/
Content-Type: application/json

{
    "title": "Rambo IV",
    "release_date": "1990-01-01",
    "resume": "Filme do Rambo, muito massa. Bom elenco",
    "genre": 2,
    "actors": [1, 2]
}

###
DELETE http://{{ hostname }}:{{ port }}/api/v1/movies/{{ movieID }}/