######################################################
######################################################
############# Request flix-api REVIEWS ###############
######################################################
######################################################
######################################################

@hostname = 127.0.0.1
@port = 8000


GET http://{{ hostname }}:{{ port }}/api/v1/reviews/

###
# @name createReview
POST http://{{ hostname }}:{{ port }}/api/v1/reviews/
Content-Type: application/json

{
    "stars": 5,
    "comment": "Muito Bom!",
    "movie": 1
}

###

@reviewID = {{ createReview.response.body.id }}

###
GET http://{{ hostname }}:{{ port }}/api/v1/reviews/{{ reviewID }}/


###
PUT http://{{ hostname }}:{{ port }}/api/v1/reviews/{{ reviewID }}/
Content-Type: application/json

{
    "stars": 5,
    "comment": "Excelente",
    "movie": 2
}

###
DELETE http://{{ hostname }}:{{ port }}/api/v1/reviews/{{ reviewID }}/